services:
  db:
    image: pgvector/pgvector:pg15
    container_name: docbridge_db
    restart: always
    environment:
      POSTGRES_USER: docbridge_admin
      POSTGRES_PASSWORD: docbridge_password
      POSTGRES_DB: docbridge_db
    ports:
      - "5433:5432"
    volumes:
      - docbridge_pgdata:/var/lib/postgresql/data

  # 【新增】Redis 消息代理与缓存
  redis:
    image: redis:7-alpine
    container_name: docbridge_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  docbridge_pgdata: